/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio_3_continuo;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dany
 */
public class Ejercicio3 extends java.awt.Frame {

    int norm = 1024;
    int suma = 775;
    int mult = 533;
    //variables
    double sem = 667;
    int superior = 1;
    int max = 1000;
    double rnd;
    double x;
    double v_esperado;
    double varianza;
    double sumaValor;
    double sumaValor1;
    double[] contador = new double[100];
    double[] frecuencia = new double[100];
    double[] frecuenciaAcumulada = new double[100];
    double[] filasX = new double[100];
    double[] probabilidadR = new double[100];
    double[] probabilidadRA = new double[100];
    DefaultTableModel tablamodel;

    public Ejercicio3() {
        initComponents();
        random();
    }

    private void random() {
//    int suma=0;
        for (int i = 0; i < max; i++) {
            sem = (mult * sem + suma) % norm;
            rnd = sem / norm;
            x = (rnd/2);
            System.out.println(x);
            filasX[i] = x;
//            sumaValor = sumaValor + x;
//            sumaValor1 = sumaValor + Math.pow(x, 2);
        }
//        v_esperado=sumaValor/max;
//        varianza= Math.sqrt(Math.abs(sumaValor1/100-Math.pow(sumaValor/100, 2)));

    }
//    
//       private void llenartabla() {
////        frecuenciaA();
////        frecuenciaAcumulada();
////        calcularProbabilidad();
////        probabilidadAcumulada();
//        for (int i = 0; i < 8; i++) {
//            if (frecuencia[i] != 0 && frecuenciaAcumulada[i] != 0) {
//                tabla3.setValueAt(String.format("%.4f", contador[i]), i, 0);
//                tabla3.setValueAt(String.format("%.4f", frecuencia[i]), i, 1);
//                tabla3.setValueAt(String.format("%.4f", frecuenciaAcumulada[i]), i, 2);
//                tabla3.setValueAt(String.format("%.4f", probabilidadR[i]), i, 3);
//                tabla3.setValueAt(String.format("%.4f", probabilidadRA[i]), i, 4);
//                
//            }
//
//        }
//        labelVE.setText(String.format("%.4f",v_esperado));
//        labelDesv.setText(String.format("%.4f",varianza));

//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtProbabilidad = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ejercicio 3 de variables continuas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Suponga que Y posee la funcion de densidad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 300, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("f(y) = ky,     0 ≤ y ≤2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("a) Encuentre el valor de k que haga de f(y) una funcion de densidad de probabilidad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("b) Calcular P(μ - 2σ < X < μ + 2σ  )");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setText("N. Simulaciones");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel1.add(txtMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, -1));

        jLabel7.setText("valor de Sem:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        txtProbabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProbabilidadActionPerformed(evt);
            }
        });
        jPanel1.add(txtProbabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 90, -1));

        jButton2.setText("Generar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        add(jPanel1, java.awt.BorderLayout.NORTH);
        add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla3);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        if (txtMax.getText() == "" && txtProbabilidad.getText() == "") {
//            JOptionPane.showMessageDialog(this, "Campo/s vacio/s");
//        } else if (max >= 1000) {
//            JOptionPane.showMessageDialog(this, "Numero de simulaciones incorrectas");
//            txtMax.setText("");
//            txtMax.requestFocus();
//        } else {
//            max = Integer.parseInt(txtMax.getText());
//            sem = Double.parseDouble(txtProbabilidad.getText());
//            if (p < 0 || p > 1) {
//                JOptionPane.showMessageDialog(this, "probabilidad incorrecta");
//                txtProbabilidad.setText("");
//                txtProbabilidad.requestFocus();
//            } else {
//                p = Double.parseDouble(txtProbabilidad.getText());
//                q = 1 - p;
//                sem = 10;
//                Random();
//                frecuenciaA();
//                frecuenciaAbsoluta();
//                calculaProbabilidad(frecuencia);
////                llenarTabla();
//            }
//        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtProbabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProbabilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProbabilidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla3;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtProbabilidad;
    // End of variables declaration//GEN-END:variables
}
